spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: a-sdf%56%@cxlar
    driver-class-name: org.postgresql.Driver
  jpa: 
    hibernate:
      ddl-auto: create-drop